spring:
  jpa:
    database: POSTGRESQL
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/goaltrail
    username: ${psql.user}
    password: ${psql.password}   
  